api/urls.py
from django.urls import path, include
from django.contrib.auth.models import User
from cpanel.models import Experiment, Quest
from rest_framework import routers, serializers, viewsets
from api.views import *


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'experimentos', ExperimentViewSet)
router.register(r'quests', QuestViewSet)

app_name = "api"

urlpatterns = [
    path('', include(router.urls)),
]

cpanel/urls.py
from django.urls import path
from . import views

app_name = "cpanel"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index")
]

serv_image_trace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("cpanel.urls", namespace="cpanel")),    
    path('admin/', admin.site.urls, name="admin"),
    path('api/', include("api.urls"), name="api")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

cpanel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms
from django.conf import settings

class Module(models.Model):
    name = models.TextField("Nome",  null=True, blank=True)
    created = models.DateTimeField("Cadastrado", auto_now_add=True)
    updated = models.DateTimeField("Atualizado", auto_now=True)
    
    class Meta:
        verbose_name = 'Bloco'
        verbose_name_plural= 'Blocos'
        ordering = ("-created","name",)
        
    def __str__(self):
        return self.name


# Create your models here.
class Quest(models.Model):
    name = models.CharField("Título do Vídeo",  null=False, blank=False, max_length=100, default="Movimento do Vídeo")
    txt = models.TextField("Orientação", null=False, blank=False)
    timer = models.IntegerField("Tempo em segundos", null=False, blank= False, default= 4)
    OPTION_CHOICES = (
        ('1', 'Verde'),
        ('2', 'Vermelho')
    )
    correct_op = models.CharField("Correta", null=False, blank=False, choices=OPTION_CHOICES, default='1', max_length=1)
    wrong_op = models.CharField("Incorreta", null=True, blank=True, choices=OPTION_CHOICES, max_length=1)
    SPEED_CHOICES = (
        ('F', 'Rápido'),
        ('N', 'Normal'),
        ('S', 'Lento')
    )
    speed = models.CharField("Velocidade", choices=SPEED_CHOICES, default='N', max_length=1)
    noise = models.BooleanField("Com ruido", default= False)
    upsidedown = models.BooleanField("Invertido", default= False)
    module = models.ForeignKey(Module, verbose_name="Bloco", null=True, on_delete=models.PROTECT, related_name='resets')
  
    videofile = models.FileField("Arquivo txt do vídeo", upload_to='quests/%Y/%m/%d')
 
    created = models.DateTimeField("Cadastrado", auto_now_add=True)
    updated = models.DateTimeField("Atualizado", auto_now=True)

    class Meta:
        verbose_name = 'Vídeo'
        verbose_name_plural= 'Vídeos'
        ordering = ("-created","name",)
        
    def __str__(self):
        return self.name

# Create your models here.
class Experiment(models.Model):
    title = models.TextField("Título",  null=False, blank=False, max_length=255)
    created = models.DateTimeField("Cadastrado", auto_now_add=True)
    updated = models.DateTimeField("Atualizado", auto_now=True)
    quests = models.ManyToManyField(Quest, verbose_name="Vídeos")
    class Meta:
        verbose_name = 'Experimento'
        verbose_name_plural= 'Experimentos'
        ordering = ("-created","title",)
        
    def __str__(self):
        return self.title

cpanel/forms.py
from django import forms
from django.contrib import admin
from .models import *
from django.contrib.admin.widgets import FilteredSelectMultiple
class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        exclude = []
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Digite o nome do módulo','minlength': 3, 'maxlength': 255}),
        }

class QuestForm(forms.ModelForm):
    class Meta:
        model = Quest
        exclude = []
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Descreva o movimento do vídeo','minlength': 3, 'maxlength': 255}),
            'txt': forms.Textarea(attrs={'rows':4, 'cols':100}),
            'wrong_op' : forms.HiddenInput(),
        }


class ExperimentForm(forms.ModelForm):
    quests = forms.ModelMultipleChoiceField(queryset=Quest.objects.all(),
                                       widget=FilteredSelectMultiple('Vídeos', False),
                                       required=False)
    class Meta:
        model = Experiment
        exclude = []
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Digite o título do experimento', 'maxlength': 255}),
            
        }

api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from django.contrib.auth.models import User
from cpanel.models import Experiment, Quest
from api.serializers import *
from rest_framework.decorators import action
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
# Create your views here.

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# ViewSets define the view behavior.
class ExperimentViewSet(viewsets.ModelViewSet):
    queryset = Experiment.objects.all()
    serializer_class = ExperimentSerializer
    
    @action(detail=True)
    def quests(self, request, pk=None):
        queryset = Experiment.objects.all()
        exp = get_object_or_404(queryset,pk=pk)
        serializer  = QuestSerializer(exp.quests, read_only=True, many=True)
        return Response(serializer.data) 


# ViewSets define the view behavior.
class QuestViewSet(viewsets.ModelViewSet):
    queryset = Quest.objects.all()
    serializer_class = QuestSerializer

cpanel/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.views.generic import TemplateView

from .models import *

class IndexView(TemplateView):
    template_name = "index.html"

cpanel/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon -->
    <link href="{% static 'img/favicon/favicon.ico'%}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'img/favicon/apple-touch-icon.png'%}" rel="apple-touch-icon">
    
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    
    <!-- Personalizado -->
    <link href="{% static 'css/style.css'%}" rel="stylesheet">

    <title>Image Trance</title>
  </head>
  <body>
    <header>
        <div class="container bg-dark">
            <nav class="navbar navbar-expand-lg navbar-dark  py-0 ">
                <a class="navbar-brand  py-0" href="#">
                    Image - Trance
                </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainMenu" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="mainMenu">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'cpanel:index' %}">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">O Projeto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Galeria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Colaboradores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Entrar</a>
                        </li>
                    </ul>
                </div>
                
            </nav>
        </div>
    </header>
    <main>
        <section class="container">
            {% block content %} {% endblock %}     
        </section>
    </main>
    <footer>
        <div class="container">
            <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <div class="col-md-5 d-flex align-items-center">
                   
                    <img src="img/logo.png" alt="" height="60"/>     
                     
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-muted" href="#">
                            <i class="fab fa-instagram fa-lg-2"></i>
                        </a>
                    </li>
                   
                    <li class="ms-3">
                        <a class="text-muted" href="#">
                            <i class="fab fa-twitter fa-lg-2"></i>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="#">
                            <i class="fab fa-facebook fa-lg-2"></i>
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="#">
                            <i class="fab fa-youtube fa-lg-2"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.6.0.min.js'%}"></script>

    <!-- Bootstrap Bundle with Popper -->
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/94b924ac3c.js" crossorigin="anonymous"></script>

    <script>
        
        {% block myscript %} {% endblock %}
        
    </script>
  </body>
</html>

cpanel/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Início {% endblock %}

{% block content %}
   

{% endblock %}

{% block myscript %}
    <script>
    
    </script>
{% endblock %}